### ISSUE TITLE
Rails 7.2: prepare CI for testing

### ISSUE THREAD

**Issue by tagliala** [activeadmin/activeadmin#8367]
### Upstream blockers:
- [x] Ransack activerecord-hackery/ransack#1491
- [x] Database Cleaner (pending release) DatabaseCleaner/database_cleaner-active_record#102
- [x] DatabaseCleaner/database_cleaner-active_record#106

### TODO:
- [x] #8368
- [x] ~Triage cucumber failures https://github.com/activeadmin/activeadmin/actions/runs/9438091597/job/25994708535?pr=8371~ They depend by database cleaner. Fixed on database cleaner main
